apiVersion: batch/v1
kind: Job
metadata:
  name: tensorizer-benchmark-read-size
spec:
  parallelism: 10
  completions: 100
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ethernet.coreweave.cloud/speed
                operator: In
                values:
                   #- 10G
                   - 40G
                   - 100G
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - LGA1
                - LAS1
                - ORD1
      containers:
        - name: benchmark
          image: ghcr.io/coreweave/tensorizer:benchmark-609b825
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash" ]
          args: [ "-c", "redis-server --daemonize yes >/dev/null & python /app/benchmark.py --json" ]
          #--redis redis://redis-master:6379" ]
          resources:
            requests:
              cpu: "8"
              memory: 64Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "8"
              memory: 64Gi
              nvidia.com/gpu: "1"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
            #- name: K8S_POD_REGION
            #  valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.labels.topology.kubernetes.io/region
            #- name: K8S_LINK_SPEED
            #  valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.labels.ethernet.coreweave.cloud/speed
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              job-name: tensorizer-benchmark-read-size
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/region
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              job-name: tensorizer-benchmark-read-size
      restartPolicy: OnFailure
